debug: false
metrics_enabled: false
graphite:
  host: carbon.hostedgraphite.com
  api_key: 7509c0ff-4db5-4cae-91ee-6e78ff13b336
  reporting_interval_in_seconds: 30
  include_metrics:
    - com.yammer
    - com.hello

sensors_db:
  driverClass: org.postgresql.Driver
  user: ingress_user
  password: hello ingress user
  url: jdbc:postgresql://chanku-test.cdawj8qazvva.us-east-1.rds.amazonaws.com:5432/chanku
  properties:
    hibernate.dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 2

  # the maximum number of connections to keep open
  maxSize: 8

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # how long a connection must be held before it can be validated
  checkConnectionHealthWhenIdleFor: 10s

  # the maximum lifetime of an idle connection
  closeConnectionIfIdleFor: 1 minute

common_db:
  driverClass: org.postgresql.Driver
  user: ingress_user
  password: hello ingress user
  url: jdbc:postgresql://chanku-test.cdawj8qazvva.us-east-1.rds.amazonaws.com:5432/chanku
  properties:
    hibernate.dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 2

  # the maximum number of connections to keep open
  maxSize: 8

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # how long a connection must be held before it can be validated
  checkConnectionHealthWhenIdleFor: 10s

  # the maximum lifetime of an idle connection
  closeConnectionIfIdleFor: 1 minute

kinesis:
  endpoint : https://kinesis.us-east-1.amazonaws.com
  streams :
    batch_pill_data : dev_batch_pill_data

app_name: TimelineWorker

max_records: 20

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    # Sets the level for 'com.example.app' to DEBUG.
    com.hello.suripu.workers: DEBUG

  file:
    enabled: true
    threshold: DEBUG
    currentLogFilename: /var/log/suripu-workers/suripu-workers-timeline.log
    # When the log file rotates, the archived log will be renamed to this and gzipped. The
    # %d is replaced with the previous day (yyyy-MM-dd). Custom rolling windows can be created
    # by passing a SimpleDateFormat-compatible format as an argument: "%d{yyyy-MM-dd-hh}".
    archivedLogFilenamePattern: /var/log/suripu-workers/suripu-workers-timeline-%d{yyyy-MM-dd}.log.gz
    # The number of archived files to keep.
    archivedFileCount: 7
    # The timezone used to format dates. HINT: USE THE DEFAULT, UTC.
    timeZone: UTC

dynamodb:
  region: us-east-1
  tables:
    alarm_info: alarm_info
    features: features
    sleep_score: sleep_score
    timeline: timeline
    sleep_hmm: sleephmm
    sleep_stats: sleep_stats
    timeline_log: timeline_log
    ring_time_history: ring_history_by_account
    timezone_history: timezone_history
    alarm_log: alarm
    feature_extraction_models: feature_extraction_models
    online_hmm_models: online_hmm_models
    calibration: calibration
    device_data: sense_data
  endpoints:
    alarm_info: http://dynamodb.us-east-1.amazonaws.com
    features : http://dynamodb.us-east-1.amazonaws.com
    sleep_score: http://dynamodb.us-east-1.amazonaws.com
    timeline: http://dynamodb.us-east-1.amazonaws.com
    sleep_hmm: http://dynamodb.us-east-1.amazonaws.com
    sleep_stats: http://dynamodb.us-east-1.amazonaws.com
    timeline_log: http://dynamodb.us-east-1.amazonaws.com
    ring_time_history: http://dynamodb.us-east-1.amazonaws.com
    timezone_history: http://dynamodb.us-east-1.amazonaws.com
    alarm_log: http://dynamodb.us-east-1.amazonaws.com
    feature_extraction_models: http://dynamodb.us-east-1.amazonaws.com
    online_hmm_models: http://dynamodb.us-east-1.amazonaws.com
    calibration: http://dynamodb.us-east-1.amazonaws.com
    device_data: http://dynamodb.us-east-1.amazonaws.com

aggregate_window_size_min: 10

sleep_score_version: v_0_1
score_threshold : 15 # minutes bucket for sleep-scores


max_no_motion_period_minutes: 90
start_process_time: 5
end_process_time: 11
start_expire_time: 5
end_expire_time: 12
max_cache_refresh_days: 20
sleep_stats_version: v_0_2

user_info_max_read_capacity_sec: 200
