metrics_enabled: false
debug: false
graphite:
  host: carbon.hostedgraphite.com
  api_key: 7509c0ff-4db5-4cae-91ee-6e78ff13b336
  reporting_interval_in_seconds: 30
  include_metrics:
    - com.yammer
    - com.hello

common_db:
  driverClass: org.postgresql.Driver
  user: common
  password: hello-common
  url: jdbc:postgresql://common-replica-1.cdawj8qazvva.us-east-1.rds.amazonaws.com:5432/common
  properties:
    hibernate.dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 2

  # the maximum number of connections to keep open
  maxSize: 4

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # how long a connection must be held before it can be validated
  checkConnectionHealthWhenIdleFor: 10s

  # the maximum lifetime of an idle connection
  closeConnectionIfIdleFor: 1 minute

sensors_db:
  driverClass: org.postgresql.Driver
  user: sensors
  password: hello-sensors
  url: jdbc:postgresql://sensors-2-replica-1.cdawj8qazvva.us-east-1.rds.amazonaws.com:5432/sensors1
  properties:
    hibernate.dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 2

  # the maximum number of connections to keep open
  maxSize: 4

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # how long a connection must be held before it can be validated
  checkConnectionHealthWhenIdleFor: 10s

  # the maximum lifetime of an idle connection
  closeConnectionIfIdleFor: 1 minute

insights_db:
  driverClass: org.postgresql.Driver
  user: common
  password: hello-common
  url: jdbc:postgresql://common-replica-1.cdawj8qazvva.us-east-1.rds.amazonaws.com:5432/common
  properties:
    hibernate.dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 2

  # the maximum number of connections to keep open
  maxSize: 4

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # how long a connection must be held before it can be validated
  checkConnectionHealthWhenIdleFor: 10s

  # the maximum lifetime of an idle connection
  closeConnectionIfIdleFor: 1 minute

kinesis:
  endpoint : https://kinesis.us-east-1.amazonaws.com
  streams :
    batch_pill_data : batch_pill_data

app_name: InsightsGeneratorConsumerProd

max_records: 100

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    # Sets the level for 'com.example.app' to DEBUG.
    com.hello.suripu.workers: DEBUG
  # Settings for logging to a file.
  file:
    enabled: true
    threshold: DEBUG
    currentLogFilename: /var/log/suripu-workers/suripu-workers-insights.log
    # When the log file rotates, the archived log will be renamed to this and gzipped. The
    # %d is replaced with the previous day (yyyy-MM-dd). Custom rolling windows can be created
    # by passing a SimpleDateFormat-compatible format as an argument: "%d{yyyy-MM-dd-hh}".
    archivedLogFilenamePattern: /var/log/suripu-workers/suripu-workers-insights-%d{yyyy-MM-dd}.log.gz
    # The number of archived files to keep.
    archivedFileCount: 7
    # The timezone used to format dates. HINT: USE THE DEFAULT, UTC.
    timeZone: UTC

dynamo_db:
  region: us-east-1
  tables:
      features : features
      calibration : prod_calibration
      insights : prod_insights
      sleep_stats : prod_sleep_stats
      preferences : prod_preferences
      sleep_score : prod_sleep_score

  endpoints:
      alarm_info : http://dynamodb.us-east-1.amazonaws.com
      features : http://dynamodb.us-east-1.amazonaws.com
      calibration: http://dynamodb.us-east-1.amazonaws.com
      insights: http://dynamodb.us-east-1.amazonaws.com
      sleep_stats : http://dynamodb.us-east-1.amazonaws.com
      preferences : http://dynamodb.us-east-1.amazonaws.com
      sleep_score : http://dynamodb.us-east-1.amazonaws.com

sleep_score_version: v_0_1
sleep_stats_version: v_0_2