metrics_enabled: false
debug: false
graphite:
  host: carbon.hostedgraphite.com
  api_key: 7509c0ff-4db5-4cae-91ee-6e78ff13b336
  reporting_interval_in_seconds: 30
  include_metrics:
    - com.yammer
    - com.hello


common_db:
  driverClass: org.postgresql.Driver
  user: ingress_user
  password: hello ingress user
  url: jdbc:postgresql://chanku-test.cdawj8qazvva.us-east-1.rds.amazonaws.com:5432/chanku
  properties:
    hibernate.dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # how long a connection must be held before it can be validated
  checkConnectionHealthWhenIdleFor: 10s

  # the maximum lifetime of an idle connection
  closeConnectionIfIdleFor: 1 minute

sensors_db:
  driverClass: org.postgresql.Driver
  user: ingress_user
  password: hello ingress user
  url: jdbc:postgresql://chanku-test.cdawj8qazvva.us-east-1.rds.amazonaws.com:5432/chanku
  properties:
    hibernate.dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # how long a connection must be held before it can be validated
  checkConnectionHealthWhenIdleFor: 10s

  # the maximum lifetime of an idle connection
  closeConnectionIfIdleFor: 1 minute

kinesis:
  endpoint : https://kinesis.us-east-1.amazonaws.com
  streams :
    pill_data : test-pill-suripu
    batch_pill_data : batch_pill_data

app_name: InsightsGeneratorConsumer

max_records: 100

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    # Sets the level for 'com.example.app' to DEBUG.
    com.hello.suripu.workers: DEBUG

insights_dynamo_db:
    endpoint : http://dynamodb.us-east-1.amazonaws.com
    region: us-east-1
    table_name: insights

sleep_score_db:
    endpoint : http://dynamodb.us-east-1.amazonaws.com
    region: us-east-1
    table_name: sleep_score
sleep_score_version: v_0_1

features_db:
    endpoint : http://dynamodb.us-east-1.amazonaws.com
    region: us-east-1
    table_name: features
